FROM azul/zulu-openjdk-alpine:11.0.7

ENV MAVEN_VERSION=3.6.3
ENV MAVEN_FILE_NAME=apache-maven-$MAVEN_VERSION-bin.tar.gz
ENV MAVEN_SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
ENV MAVEN_BASE_URL=https://archive.apache.org/dist/maven/maven-3

WORKDIR /tmp

SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
RUN set -o \
    && mkdir -p /usr/share/maven /usr/share/maven/ref \
    && wget $MAVEN_BASE_URL/$MAVEN_VERSION/binaries/$MAVEN_FILE_NAME \
    && echo "$MAVEN_SHA  $MAVEN_FILE_NAME" | sha512sum -c - \
    && tar -xzf $MAVEN_FILE_NAME -C /usr/share/maven --strip-components=1 \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn \
    && rm -f $MAVEN_FILE_NAME
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "/root/.m2"

WORKDIR /projectName

COPY ./pom.xml /projectName/
COPY ./api-rest/pom.xml /projectName/api-rest/
COPY ./service-dummy/pom.xml /projectName/service-dummy/

RUN echo $(ls /projectName)

RUN mvn dependency:go-offline
