---
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: web
    container_name: web
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="${JVM_ARGS}"
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - WEB_PORT
    ports:
      - 127.0.0.1:${WEB_PORT}:${WEB_PORT}
      - 127.0.0.1:30005:30005
    volumes:
      - ./:/projectName
      - maven-cache:/root/.m2
    depends_on:
      - migrations

  migrations:
    build: ./migrations
    command: -url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_USER} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=30 migrate
    depends_on:
      - db

  db:
    image: "postgres:12.2-alpine"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata:
  maven-cache:
