apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: statefun
spec:
  type: ClusterIP
  ports:
    - name: endpoint
      port: 8000
  selector:
    app: statefun
    component: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: statefun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefun
      component: hello
  template:
    metadata:
      labels:
        app: statefun
        component: hello
    spec:
      containers:
        - name: hello
          image: hello
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: endpoint
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60

