---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: statefun
spec:
  type: ClusterIP
  ports:
    - name: endpoint
      port: 9000
  selector:
    app: statefun
    component: minio
