apiVersion: v1
kind: ConfigMap
metadata:
  name: module-config
data:
  module.yaml: |+
    kind: io.statefun.endpoints.v2/http
    spec:
      functions: example/*
      urlPathTemplate: http://hello.{{.Release.Namespace}}.svc.cluster.local:8000/statefun
    ---
    kind: io.statefun.kafka.v1/ingress
    spec:
      id: example/in
      address: kafka-broker.{{.Release.Namespace}}.svc.cluster.local:9092
      consumerGroupId: my-group-id
      topics:
        - topic: names
          valueType: example/MyMessage
          targets:
            - example/hello

