# Welcome to Serverless!
#
# This file is the main config file for your service.
service: Markup

# Serverless framework version
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-1

functions:
  generateMarkupLineItems:
    handler: handler.generateMarkupLineItems
    events:
      - http:
          path: /{any+}
          method: ANY
