---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: statefun
  labels:
    app: kafka-broker
spec:
  ports:
    - port: 9092
      name: plaintext
  selector:
    app: kafka-broker
