---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafkacat
  name: kafkacat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkacat
  template:
    metadata:
      labels:
        app: kafkacat
    spec:
      containers:
        - image: confluentinc/cp-kafkacat:7.1.5
          command: ["tail"]
          args: ["-F", "anything"]
          imagePullPolicy: IfNotPresent
          name: kafkacat
